services:
  app:
    container_name: byzip-be-dev-app
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.staging
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/byzip_dev
      NODE_ENV: development
    networks:
      - byzip-network

  postgres:
    container_name: byzip-be-dev-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: byzip_dev
    volumes:
      - ./postgres-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - byzip-network

networks:
  byzip-network:
    external: true
