services:
  nginx:
    container_name: byzip-nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - byzip-network

  app:
    container_name: byzip-be-app
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/byzip
      NODE_ENV: production
    networks:
      - byzip-network

  postgres:
    container_name: byzip-be-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: byzip
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - byzip-network

networks:
  byzip-network:
    name: byzip-network
    driver: bridge
